name: dargon2_core
description: The bindings for argon2's C reference library. Does not include the library loading itself.
version: 2.0.2
homepage: https://github.com/tmthecoder/dargon2_core
repository: https://github.com/tmthecoder/dargon2_core

environment:
  sdk: '>=2.14.0 <3.0.0'

dependencies:
  ffi: '^1.1.2'
  dargon2_interface: '^1.0.1'

dev_dependencies:
  pedantic: ^1.10.0
  test: ^1.16.0
